# Generated by Django 5.2 on 2025-05-02 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AitOlduguYer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DsiNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=50, unique=True, verbose_name='DSİ No')),
                ('model_adi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model')),
                ('aciklama', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açıklama')),
            ],
        ),
        migrations.CreateModel(
            name='MakineTakip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(blank=True, max_length=100, null=True)),
                ('cins', models.CharField(blank=True, max_length=100, null=True)),
                ('marka', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('tarih', models.DateField(blank=True, null=True)),
                ('calistigi_yer', models.CharField(blank=True, max_length=200, null=True)),
                ('konum', models.CharField(blank=True, editable=False, max_length=200, null=True)),
                ('isin_durumu', models.CharField(choices=[('devam', 'Devam ediyor'), ('bitti', 'Bitti')], default='devam', max_length=10)),
                ('ise_baslama', models.DateField(blank=True, null=True)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('ait_oldugu_yer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ait_oldugu_yer', to='core.aitolduguyer')),
                ('dsi_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dsino')),
            ],
        ),
    ]
