# Generated by Django 5.2 on 2025-05-02 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsinAdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adi', models.CharField(max_length=200, verbose_name='İşin Adı')),
            ],
            options={
                'verbose_name': 'İş Adı',
                'verbose_name_plural': 'İş Adları',
            },
        ),
        migrations.CreateModel(
            name='Planlamalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sira_no', models.IntegerField(verbose_name='Sıra No')),
                ('bölge_no', models.IntegerField(verbose_name='Bölge No')),
                ('il_adi', models.CharField(max_length=100, verbose_name='İl Adı')),
                ('ilce_adi', models.CharField(max_length=100, verbose_name='İlçe Adı')),
                ('taskin_isi_adi', models.CharField(max_length=200, verbose_name='Taşkın İşi Adı')),
                ('ilk_inceleme_raporu', models.CharField(choices=[('var', 'VaR'), ('yok', 'YoK')], verbose_name='İlk İnceleme Raporu')),
                ('on_inceleme_raporu', models.CharField(choices=[('var', 'VaR'), ('yok', 'YoK')], verbose_name='Ön İnceleme Raporu')),
                ('kamulastirma_problemi', models.CharField(choices=[('var', 'VaR'), ('yok', 'YoK')], verbose_name='Kamulaştırma Problemi')),
                ('yaklasik_insaat_maliyeti', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Yaklaşık İnşaat Maliyeti (TL)')),
                ('korunan_yerlesim_yeri', models.CharField(max_length=200, verbose_name='Korunan Yerleşim Yeri')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
            ],
            options={
                'verbose_name': 'Planlama',
                'verbose_name_plural': 'Planlamalar',
            },
        ),
        migrations.AlterModelOptions(
            name='aitolduguyer',
            options={'verbose_name': 'Ait Olduğu Yer', 'verbose_name_plural': 'Ait Olduğu Yerler'},
        ),
        migrations.AlterModelOptions(
            name='dsino',
            options={'verbose_name': 'DSİ No', 'verbose_name_plural': 'DSİ Nolar'},
        ),
        migrations.AlterModelOptions(
            name='makinetakip',
            options={'verbose_name': 'Makine Takibi', 'verbose_name_plural': 'Makine Takipleri'},
        ),
        migrations.AlterField(
            model_name='aitolduguyer',
            name='adi',
            field=models.CharField(max_length=100, verbose_name='Yer Adı'),
        ),
        migrations.AlterField(
            model_name='makinetakip',
            name='aciklama',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='makinetakip',
            name='ait_oldugu_yer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ait_oldugu_yer', to='core.aitolduguyer', verbose_name='Ait Olduğu Yer'),
        ),
        migrations.AlterField(
            model_name='makinetakip',
            name='calistigi_yer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Çalıştığı Yer'),
        ),
        migrations.AlterField(
            model_name='makinetakip',
            name='cins',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cins'),
        ),
        migrations.AlterField(
            model_name='makinetakip',
            name='dsi_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dsino', verbose_name='DSİ No'),
        ),
        migrations.AlterField(
            model_name='makinetakip',
            name='ise_baslama',
            field=models.DateField(blank=True, null=True, verbose_name='İşe Başlama Tarihi'),
        ),
        migrations.AlterField(
            model_name='makinetakip',
            name='isin_durumu',
            field=models.CharField(choices=[('devam', 'Devam ediyor'), ('bitti', 'Bitti')], default='devam', max_length=10, verbose_name='İş Durumu'),
        ),
        migrations.AlterField(
            model_name='makinetakip',
            name='konum',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True, verbose_name='Konum'),
        ),
        migrations.AlterField(
            model_name='makinetakip',
            name='marka',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='makinetakip',
            name='model',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='makinetakip',
            name='tarih',
            field=models.DateField(blank=True, null=True, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='makinetakip',
            name='tur',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tür'),
        ),
        migrations.CreateModel(
            name='Yatirim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toplam_kesif_ihale_bedeli', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Toplam Keşif ve İhale Bedeli')),
                ('yil_sonuna_kadar_harcama', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Yıl Sonuna Kadar Harcama')),
                ('yil_kesif_bedeli', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Yıl Keşif Bedeli')),
                ('yil_nakti', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Yıl Nakdi')),
                ('revize_odenk', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Revize Ödenek')),
                ('bbb_ve_sonrasi_kesif_bedeli', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='BBB ve Sonrası Keşif Bedeli')),
                ('yapilis_sekli', models.CharField(choices=[('i', 'İ'), ('bi', 'Bİ')], verbose_name='Yapılış Şekli')),
                ('baslama_tarihi', models.IntegerField(choices=[(2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031'), (2032, '2032'), (2033, '2033'), (2034, '2034'), (2035, '2035'), (2036, '2036'), (2037, '2037'), (2038, '2038'), (2039, '2039'), (2040, '2040'), (2041, '2041'), (2042, '2042'), (2043, '2043'), (2044, '2044'), (2045, '2045'), (2046, '2046'), (2047, '2047'), (2048, '2048'), (2049, '2049')], verbose_name='Başlama Yılı')),
                ('bitis_tarihi', models.IntegerField(choices=[(2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031'), (2032, '2032'), (2033, '2033'), (2034, '2034'), (2035, '2035'), (2036, '2036'), (2037, '2037'), (2038, '2038'), (2039, '2039'), (2040, '2040'), (2041, '2041'), (2042, '2042'), (2043, '2043'), (2044, '2044'), (2045, '2045'), (2046, '2046'), (2047, '2047'), (2048, '2048'), (2049, '2049')], verbose_name='Bitiş Yılı')),
                ('talep', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Talep')),
                ('tenkis', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Tenkis')),
                ('isin_adi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yatirimlar', to='core.isinadi', verbose_name='İşin Adı')),
            ],
            options={
                'verbose_name': 'Yatırım',
                'verbose_name_plural': 'Yatırımlar',
            },
        ),
    ]
