# Generated by Django 5.2 on 2025-05-03 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_isinadi_planlamalar_alter_aitolduguyer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kanun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adi', models.CharField(max_length=100, unique=True, verbose_name='Kanun')),
                ('dosya', models.FileField(blank=True, null=True, upload_to='', verbose_name='Dosya')),
            ],
            options={
                'verbose_name': 'Kanun',
                'verbose_name_plural': 'Kanunlar',
            },
        ),
        migrations.RemoveField(
            model_name='makinetakip',
            name='ait_oldugu_yer',
        ),
        migrations.RenameField(
            model_name='makinetakip',
            old_name='dsi_no',
            new_name='makina',
        ),
        migrations.RemoveField(
            model_name='dsino',
            name='aciklama',
        ),
        migrations.RemoveField(
            model_name='makinetakip',
            name='cins',
        ),
        migrations.RemoveField(
            model_name='makinetakip',
            name='marka',
        ),
        migrations.RemoveField(
            model_name='makinetakip',
            name='model',
        ),
        migrations.RemoveField(
            model_name='makinetakip',
            name='tur',
        ),
        migrations.AddField(
            model_name='dsino',
            name='ait_oldugu_yer',
            field=models.CharField(default='merkez', max_length=100, verbose_name='Yer Adı'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dsino',
            name='cins',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tür'),
        ),
        migrations.AddField(
            model_name='dsino',
            name='marka',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tür'),
        ),
        migrations.AddField(
            model_name='dsino',
            name='tur',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tür'),
        ),
        migrations.CreateModel(
            name='Kanunlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kanun')),
            ],
            options={
                'verbose_name': 'Kanun',
                'verbose_name_plural': 'Kanunlar',
            },
        ),
        migrations.DeleteModel(
            name='AitOlduguYer',
        ),
    ]
