# Generated by Django 5.2 on 2025-05-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_kanun_remove_makinetakip_ait_oldugu_yer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yatirim',
            name='isin_adi',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True, verbose_name='İşin Adı'),
        ),
        migrations.AlterField(
            model_name='yatirim',
            name='yapilis_sekli',
            field=models.CharField(choices=[('kamulastırma', 'Kamulaştırma'), ('kamulastırma_disi', 'Kamulaştırma Dışı')], verbose_name='Yapılış Şekli'),
        ),
        migrations.DeleteModel(
            name='IsinAdi',
        ),
    ]
