# Generated by Django 5.2 on 2025-05-03 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_yatirim_isin_adi_alter_yatirim_yapilis_sekli_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kanun',
            new_name='KanunMaddeleri',
        ),
        migrations.AlterModelOptions(
            name='kanunmaddeleri',
            options={'verbose_name': 'Kanun Maddesi', 'verbose_name_plural': 'Kanun Maddeleri'},
        ),
    ]
