# Generated by Django 5.2 on 2025-05-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_kanun_kanunmaddeleri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanunmaddeleri',
            name='no',
            field=models.CharField(default=6446, max_length=50, unique=True, verbose_name='Kanun No'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kanunmaddeleri',
            name='adi',
            field=models.CharField(max_length=100, unique=True, verbose_name='Kanun Adı'),
        ),
    ]
