# Generated by Django 5.2 on 2025-05-03 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_kanunmaddeleri_no_alter_kanunmaddeleri_adi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanunmaddeleri',
            name='dosya',
        ),
        migrations.AlterField(
            model_name='dsino',
            name='cins',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cins'),
        ),
        migrations.AlterField(
            model_name='dsino',
            name='marka',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marka'),
        ),
        migrations.CreateModel(
            name='KanunDosyalari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya', models.FileField(upload_to='', verbose_name='Dosya')),
                ('kanun_maddesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dosyalar', to='core.kanunmaddeleri')),
            ],
        ),
    ]
