# Generated by Django 5.2 on 2025-05-03 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_kanunmaddeleri_dosya_alter_dsino_cins_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kanundosyalari',
            options={'verbose_name': 'Kanun Dosya', 'verbose_name_plural': 'Kanun Dosyaları'},
        ),
    ]
