# Generated by Django 4.2.20 on 2025-05-03 09:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_kanundosyalari_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makinetakip',
            name='konum',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, editable=False, null=True, srid=4326, verbose_name='Konum'),
        ),
    ]
