# Generated by Django 4.2.20 on 2025-05-06 17:39

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_makinetakip_konum_delete_kanunlar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makinetakip',
            name='konum',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(35.2433 38.9637)', srid=4326, verbose_name='Konum'),
            preserve_default=False,
        ),
    ]
