# Generated by Django 4.2.20 on 2025-05-06 17:40

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_makinetakip_konum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makinetakip',
            name='konum',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Konum'),
        ),
    ]
