# Generated by Django 4.2.20 on 2025-05-06 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_makinetakip_konum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makinetakip',
            name='makina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takipler', to='core.dsino', verbose_name='DSİ No'),
        ),
    ]
