# Generated by Django 4.2.20 on 2025-05-07 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_makinetakip_makina'),
    ]

    operations = [
        migrations.CreateModel(
            name='Il',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='İl Adı')),
            ],
        ),
        migrations.RemoveField(
            model_name='planlamalar',
            name='il_adi',
        ),
        migrations.RemoveField(
            model_name='planlamalar',
            name='ilce_adi',
        ),
        migrations.AlterField(
            model_name='planlamalar',
            name='ilk_inceleme_raporu',
            field=models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], max_length=3, verbose_name='İlk İnceleme Raporu'),
        ),
        migrations.AlterField(
            model_name='planlamalar',
            name='kamulastirma_problemi',
            field=models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], max_length=3, verbose_name='Kamulaştırma Problemi'),
        ),
        migrations.AlterField(
            model_name='planlamalar',
            name='on_inceleme_raporu',
            field=models.CharField(choices=[('var', 'Var'), ('yok', 'Yok')], max_length=3, verbose_name='Ön İnceleme Raporu'),
        ),
        migrations.CreateModel(
            name='Ilce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='İlçe Adı')),
                ('il', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilceler', to='core.il')),
            ],
        ),
        migrations.AddField(
            model_name='planlamalar',
            name='il',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.il'),
        ),
        migrations.AddField(
            model_name='planlamalar',
            name='ilce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ilce'),
        ),
    ]
