# Generated by Django 4.2.20 on 2025-05-07 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_il_remove_planlamalar_il_adi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='il',
            old_name='ad',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='ilce',
            old_name='ad',
            new_name='name',
        ),
    ]
