# Generated by Django 4.2.20 on 2025-05-07 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_ad_il_name_rename_ad_ilce_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planlamalar',
            old_name='bölge_no',
            new_name='bolge_no',
        ),
    ]
