# Generated by Django 4.2.20 on 2025-05-08 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_bölge_no_planlamalar_bolge_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Makine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=50, unique=True, verbose_name='Makine No')),
                ('model_adi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model')),
                ('tur', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tür')),
                ('cins', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cins')),
                ('marka', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marka')),
                ('ait_oldugu_yer', models.CharField(max_length=100, verbose_name='Yer Adı')),
            ],
            options={
                'verbose_name': 'Makine',
                'verbose_name_plural': 'Makineler',
            },
        ),
        migrations.AlterField(
            model_name='makinetakip',
            name='makina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takipler', to='core.makine', verbose_name='Makine No'),
        ),
        migrations.DeleteModel(
            name='DsiNo',
        ),
    ]
