# Generated by Django 4.2.20 on 2025-05-08 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_makine_alter_makinetakip_makina_delete_dsino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makinetakip',
            name='makina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='takipler', to='core.makine', verbose_name='Makine No'),
        ),
    ]
