# Generated by Django 4.2.20 on 2025-05-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_makinetakip_makina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makinetakip',
            name='tarih',
        ),
        migrations.AddField(
            model_name='makinetakip',
            name='ise_bitis',
            field=models.DateField(blank=True, null=True, verbose_name='İşin Bittiği Tarih'),
        ),
    ]
