# Generated by Django 4.2.20 on 2025-05-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_makinetakip_tarih_makinetakip_ise_bitis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makinetakip',
            name='isin_durumu',
            field=models.CharField(choices=[('devam', 'Devam ediyor'), ('bitti', 'Bitti')], default='bitti', max_length=10, verbose_name='İş Durumu'),
        ),
    ]
