# Generated by Django 4.2.21 on 2025-05-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_makinetakip_isin_durumu'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanundosyalari',
            name='dosya_tipi',
            field=models.CharField(default='jpg', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kanundosyalari',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='makine',
            name='no',
            field=models.CharField(error_messages={'unique': 'Bu makine numarası zaten mevcut.'}, max_length=50, unique=True, verbose_name='Makine No'),
        ),
    ]
