# Generated by Django 4.2.21 on 2025-05-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_kanundosyalari_dosya_tipi_alter_kanundosyalari_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='makinetakip',
            name='is_tanimi',
            field=models.TextField(blank=True, null=True, verbose_name='İşin Tanımı'),
        ),
    ]
