# Generated by Django 4.2.21 on 2025-05-11 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_makinetakip_is_tanimi'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsTanimi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tanim', models.CharField(max_length=255, verbose_name='İş Tanımı')),
            ],
            options={
                'verbose_name': 'İş Tanımı',
                'verbose_name_plural': 'İş Tanımları',
            },
        ),
        migrations.AlterField(
            model_name='makinetakip',
            name='is_tanimi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.istanimi', verbose_name='İş Tanımı'),
        ),
    ]
