# Generated by Django 4.2.21 on 2025-05-13 21:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_istanimi_alter_makinetakip_is_tanimi'),
    ]

    operations = [
        migrations.AddField(
            model_name='makinetakip',
            name='guncelleme_tarihi',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AddField(
            model_name='makinetakip',
            name='olusturma_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Oluşturma Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planlamalar',
            name='guncelleme_tarihi',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AddField(
            model_name='planlamalar',
            name='olusturma_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Oluşturma Tarihi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yatirim',
            name='guncelleme_tarihi',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi'),
        ),
        migrations.AddField(
            model_name='yatirim',
            name='olusturma_tarihi',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Oluşturma Tarihi'),
            preserve_default=False,
        ),
    ]
