# Generated by Django 4.2.21 on 2025-05-16 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_makinetakip_guncelleme_tarihi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True, verbose_name='Marka Adı')),
            ],
        ),
        migrations.CreateModel(
            name='ModelAdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True, verbose_name='Model Adı')),
                ('marka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeller', to='core.marka')),
            ],
        ),
        migrations.AlterField(
            model_name='makine',
            name='marka',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.marka', verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='makine',
            name='model_adi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modeladi', verbose_name='Model'),
        ),
    ]
