# Generated by Django 4.2.21 on 2025-05-17 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_marka_modeladi_alter_makine_marka_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsinAdi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ad', models.CharField(max_length=255, verbose_name='İşin Adı')),
            ],
            options={
                'verbose_name': 'İşin Adı',
                'verbose_name_plural': 'İş Adları',
            },
        ),
        migrations.AlterField(
            model_name='yatirim',
            name='isin_adi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.isinadi', verbose_name='İşin Adı'),
        ),
    ]
