# Generated by Django 4.2.21 on 2025-05-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_isinadi_alter_yatirim_isin_adi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanunmaddeleri',
            name='no',
            field=models.CharField(error_messages={'unique': 'Bu kanun numarası zaten mevcut.'}, max_length=50, unique=True, verbose_name='Kanun No'),
        ),
    ]
