# Generated by Django 4.2.21 on 2025-05-19 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_kanunmaddeleri_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='il',
            options={'verbose_name': 'Il', 'verbose_name_plural': 'Iller'},
        ),
        migrations.AlterModelOptions(
            name='ilce',
            options={'verbose_name': 'Ilce', 'verbose_name_plural': 'Ilceler'},
        ),
        migrations.AlterModelOptions(
            name='marka',
            options={'verbose_name': 'Marka', 'verbose_name_plural': 'Markalar'},
        ),
        migrations.AlterModelOptions(
            name='modeladi',
            options={'verbose_name': 'Model', 'verbose_name_plural': 'Modeller'},
        ),
    ]
