# Generated by Django 4.2.21 on 2025-05-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_il_options_alter_ilce_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isinadi',
            name='ad',
            field=models.CharField(max_length=255, unique=True, verbose_name='İşin Adı'),
        ),
    ]
